FROM ubuntu:latest

RUN apt update

RUN apt install -y python3 python3-pip

RUN apt install -y vim

RUN pip3 install gdcm

RUN pip3 install flask

RUN pip3 install glob2 

RUN pip3 install opencv-python 

RUN pip3 install pickle5

RUN pip3 install pytest-shutil

RUN pip3 install asyncio

RUN pip3 install pandas

RUN pip3 install numpy

#RUN pip3 install jsonlib

RUN pip3 install boto3

RUN pip3 install matplotlib

RUN pip3 install werkzeug

RUN pip3 install pydicom

RUN pip3 install requests

RUN pip3 install lib-platform

EXPOSE 5011

RUN apt install libgl1-mesa-glx

WORKDIR /development
